image: ubuntu

#shallow_clone: true

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
- sh: appveyor UpdateBuild --version "1.2.${APPVEYOR_BUILD_NUMBER}" --message "Hi there, Bash!"
- sh: ls /tmp -al
- sh: ls -al
- sh: echo -e "Default \033[42mGreen"
- echo Hi there! This is white text on green background!
- sh: echo -e "Default \e[49mDefault"
- ps: |
    Write-Host "Setting 'aaa' variable in one script"
    $env:aaa = 'Hello, World!'

- sh: whoami
#- sh: lsb_release -a
#- sh: printenv
#- sh: touch /tmp/tmp-1
#- ls /tmp/ -al
#- sh: powershell ./test.ps1
- appveyor PushArtifact test.txt
- echo "Should be run on both Windows and Mac"
#- sh: ENV

- ps: |
    Write-Host "Displaying 'aaa' variable in another script: $env:aaa"

#- batch: should be skipped by both platforms
#- ps: 'gci env:'
#- ls
#- sh: ls $HOME
#- sh: echo "This is Bash script!"
- npm --version
- sh: appveyor AddTest --Name "Test Bash A" -Framework "NUnit" --FileName "Assembly1.dll" --Outcome "Running"
- sh: appveyor UpdateTest --Name "Test Bash A" --FileName "Assembly1.dll" --Outcome "Passed" --Duration 1200 --StdOut "This is StdOut" --StdErr "This is StdErr"
#- ps: 'Write-Host "This is run on Windows only: $env:USERPROFILE"'
#- cmd: 'echo This run on Windows too: %USERPROFILE%'
#- sh: appveyor PackageArtifacts
#- sh: appveyor PushArtifact readme.md --fileName readme.md
#- sh: appveyor PushArtifact --path '**/*.md'
#- stat /tmp
#- rm /tmp/tmp-*
#- ls /tmp/ -al
- sh: appveyor AddMessage --message 'test message from bash 1' --category 'Error' --details "This is some details!"
- sh: appveyor AddCompilationMessage --message 'test message from batch 1' --category 'Information' --details "This is some details!" --line 10 --column 1
- ps: ./build-agent-api.ps1
- appveyor SetVariable --value="surprise"
- echo ${test_variable_1}
- echo ${bash_var_2}

build: off

test: off
