image: ubuntu

#shallow_clone: true

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
#- sh: appveyor --version
- sh: appveyor version

#- sh: ls /tmp -al
- sh: ls -al
#- sh: appveyor UpdateBuild --version "1.2.${APPVEYOR_BUILD_NUMBER}" --message "Hi there, Bash!"
- sh: echo -e "Default \033[42mGreen"
- echo Hi there! This is white text on green background!
- sh: echo -e "Default \e[49mDefault"
- ps: |
    Write-Host "Setting 'aaa' variable in one script" -ForegroundColor Green
    $env:aaa = 'Hello, World!'

- sh: whoami
#- sh: lsb_release -a
#- sh: printenv
#- sh: touch /tmp/tmp-1
#- ls /tmp/ -al
#- sh: powershell ./test.ps1
#- appveyor PushArtifact test.txt
- echo "Should be run on both Windows and Mac"
#- sh: ENV

- ps: |
    Write-Host "Displaying 'aaa' variable in another script: $env:aaa"

#- batch: should be skipped by both platforms
#- ps: 'gci env:'
#- ls
#- sh: ls $HOME
#- sh: echo "This is Bash script!"
- npm --version
#- sh: appveyor AddTest --name "Test Bash A" --framework "NUnit" --fileName "Assembly1.dll" --outcome "Running"
#- sh: appveyor UpdateTest --name "Test Bash A" --fileName "Assembly1.dll" --outcome "Passed" --duration 1200 --stdOut "This is StdOut" --stdErr "This is StdErr"
#- ps: 'Write-Host "This is run on Windows only: $env:USERPROFILE"'
#- cmd: 'echo This run on Windows too: %USERPROFILE%'
#- sh: appveyor PackageArtifacts
#- sh: appveyor PushArtifact readme.md --fileName readme.md
#- sh: appveyor PushArtifact --path '**/*.md'
#- stat /tmp
#- rm /tmp/tmp-*
#- ls /tmp/ -al
- pwsh: $env:test_variable_1 = "test_variable_1 secret value!"
- sh: export bash_var_2=This is bash variable!
#- sh: appveyor AddMessage --message 'test message from bash 1' --category 'Error' --details "This is some details!"
#- sh: appveyor AddCompilationMessage --message 'test message from batch 1' --category 'Information' --details "This is some details!" --line 10 --column 1
- pwsh: |
    Write-Host "Something on the first line"
    #./build-agent-api.ps1
#- appveyor SetVariable --name="bash_var_2" --value="surprise"
- echo ${test_variable_1}
- echo ${bash_var_2}

build: off

test: off

on_success:
- echo On success script!

on_failure:
- echo On failure script!

on_finish:
- ps: Write-Host 'I''m on_finish script!'
#- ps: Write-Message "I'm problematic on_finish script!"

